### ISSUE TITLE
Blacklist* Appeal

### ISSUE THREAD

**Issue by comfykayyy** [DanielaGC/ChinoKafuu#237]
Apparently, I got banned from the server and I can't even join it with a VPN and a new account so...
Ok so, I know I was being so freaking childish yesterday and I regret that, I was with friends, one of them made an avatar for us which wasn't a dick like everyone said it was so we got "mad" but fine. I'm not asking to be re-added to Chino Kafuu Development Team neither Rabbit House Coffee Discord Staff. I'm simply asking for a removal of my ban that made me learn some things (we are human, we all commit mistakes, right?) Once again, I know I was being childish af and I'm sorry for might pissing off someone and for making such a bad thing.
Hope you understand,
as1de

**Comment by comfykayyy** [comment]
@DanielaGC

**Comment by comfykayyy** [comment]
also, I'm appealing mainly because it is a welcoming community that I've passed most of my time with...

**Comment by BlueSlimee** [comment]
The problem here isn't your petty behavior, but how instead of just leaving the server or staying quiet after people criticized your avatar (which surely wasn't work appropriated), you guys started sending porn and, judging by the name of one of the accounts involved, I wouldn't be surprised if you guys were racist in there too.

Reiterating that you were the one that invited them over. You guys were there as a group and you will be judged and penalized as such. Everyone involved will be getting the same response and punishment.

As the assignee of your case, I don't think you can go back yet. The entirety of the mod team thinks that.
You were with us for a long time, you know what Discord does to people sending NSFW content in places they shouldn't. This is the kind of stuff that gets servers deleted. We do not want that.

You are not getting permanently banned (probably). I will wait a month or so and check with @DanielaGC and @NavyCake to see whether you should get unbanned but until then, your appeal is denied.
